### ISSUE TITLE
something wrong when I specify the latex output

### ISSUE THREAD

**Issue by xeon-ye** [UniModal4Reasoning/StructEqTable-Deploy#1]
![test2](https://github.com/user-attachments/assets/56aa4bfa-bc74-4112-b496-59e7d11956cd)
Table 0 LaTex code:
\begin{tabular}{|c|c|c|c|c|c|c|c|c|}\hline \textbf{品牌} & \textbf{耶径} & \textbf{驾驶} & \textbf{FSUM} & \textbf{规格} & \textbf{数量} & \textbf{含假单位} & \textbf{不会铝金属} & \textbf{算法} \\\hline \textbf{盒太昂} & \textbf{83强卡} & \textbf{一弱晶} & \textbf{225} & \textbf{760} & \textbf{10.530} & \textbf{6,500} & \textbf{60.570.00} & \textbf{1、评价移动到医疗} \\\hline  & & & & & & & - & 2, 结构以实际到成为 \\\hline  & & & & & & & - & \textbf{准} \\\hline  & & & & & & & - & 3, 移动尺寸, 转移 \\\hline  & & & & & & & - & 6000米, 生命来源 \\\hline  & & & & & & & - & 4, 转移晶, 胃 \\\hline  & & & & & & & - & 5, 送敛弱背检测质量 \\\hline  & & & & & & & - & 标准环境下检测的膜 \\\hline  & & & & & & & - & \textbf{屋} \\\hline  & & & & & & & - & 6, 荧比例质量的会 \\\hline  & & & & & & & - & \textbf{VCI330-2009标准} \\\hline  & & & & & & & - & 7, 氢款方式为跃到废 \\\hline  & &

**Comment by BOBrown** [comment]
@xeon-ye 
What is the value of max_new_tokens that you set in the function ```build_model(args.ckpt_path, max_new_tokens=4096, max_time=60)```

**Comment by xeon-ye** [comment]
I don't change anything,used default values:  def __init__(self, model_path='U4R/StructTable-base', max_new_tokens=4096, max_time=60):

**Comment by PrinceVictor** [comment]
This is an OOD (Out-of-Distribution) table image. Our current model is not yet able to correctly predict this image. We will continue to optimize our model to support more domains in the soon. Please stay tuned for our updates.

**Comment by xeon-ye** [comment]
Yes,The image had been recitified with opencv,because it is skewed during the capturing period.
