### ISSUE TITLE
 Hello, if you set the output to markdown format, but the final output data is not in MARKDOWN format?

### ISSUE THREAD

**Issue by hl-gl** [UniModal4Reasoning/StructEqTable-Deploy#12]
Hello, if you set the output to markdown format, but the final output data is not in MARKDOWN format?

**Comment by sky-fly97** [comment]
> Hello, if you set the output to markdown format, but the final output data is not in MARKDOWN format?

Hi, Can you show your example?

**Comment by hl-gl** [comment]
> > Hello, if you set the output to markdown format, but the final output data is not in MARKDOWN format?
> 
> Hi, Can you show your example?

However, the latex format file cannot be displayed correctly when converted to markdown format file

**Comment by sky-fly97** [comment]
> > > Hello, if you set the output to markdown format, but the final output data is not in MARKDOWN format?
> > 
> > 
> > Hi, Can you show your example?
> 
> However, the latex format file cannot be displayed correctly when converted to markdown format file

Currently our model only supports latex format output. Since markdown format doesn't support merged cells, as shown in the code of `demo.py`, some simple tables that do not contain merged cells can be converted by the pypandoc tool, but if it is a complex table may not work.

**Comment by hl-gl** [comment]
> > > > Hello, if you set the output to markdown format, but the final output data is not in MARKDOWN format?
> > > 
> > > 
> > > Hi, Can you show your example?
> > 
> > 
> > However, the latex format file cannot be displayed correctly when converted to markdown format file
> 
> Currently our model only supports latex format output. Since markdown format doesn't support merged cells, as shown in the code of `demo.py`, some simple tables that do not contain merged cells can be converted by the pypandoc tool, but if it is a complex table may not work.

![image](https://github.com/user-attachments/assets/f3f8b9bd-240d-45e4-b119-5b61ff765228)
![image](https://github.com/user-attachments/assets/81d2c382-4d59-434b-94d0-4321feafc790)
![image](https://github.com/user-attachments/assets/6914f58a-c58a-451c-8c05-63ec1ce3b4d0)
The third picture shows the markdown output using the method in the first picture. According to the results, the correct markdown file was not successfully output. How can I solve this problem?

**Comment by sky-fly97** [comment]
This is my output.
![Screenshot from 2024-09-03 14-44-29](https://github.com/user-attachments/assets/4f3b7ef0-661f-4aee-af4d-3edda636e297)

**Comment by sky-fly97** [comment]
You can see if the latex code is correct, if it is correct it may be a problem with pypandoc, the version I use is 1.13.

**Comment by hl-gl** [comment]
> You can see if the latex code is correct, if it is correct it may be a problem with pypandoc, the version I use is 1.13.

Thank you, the problem is solved. When downloading the model file, version 1 and version 2 should be confused.

**Comment by PrinceVictor** [comment]
Due to the lack of recent updates, this issue will be closed.
