### ISSUE TITLE
Demo command does not work

### ISSUE THREAD

**Issue by Faultiness** [UniModal4Reasoning/StructEqTable-Deploy#15]
Hi. I have cloned the git and downloaded the weight from hf. When I try the demo command, it reports: 
```
Traceback (most recent call last):
  File "/Users/<user>/StructEqTable-Deploy/tools/demo/demo.py", line 71, in <module>
    main()
  File "/Users/<user>/StructEqTable-Deploy/tools/demo/demo.py", line 29, in main
    model = build_model(
  File "/Users/<user>/anaconda3/envs/pdf/lib/python3.10/site-packages/struct_eqtable/__init__.py", line 6, in build_model
    model = StructTable(model_ckpt, **kwargs)
TypeError: StructTable.__init__() got an unexpected keyword argument 'tensorrt_path'
```
Would anyone be able to help? Thanks!

**Comment by PrinceVictor** [comment]
It seems you are using an older version (v0.2) of the code. Please update your code to the latest version.

**Comment by Faultiness** [comment]
Thanks for your reply. I AM using the latest version now. Please check:
<img width="461" alt="图片" src="https://github.com/user-attachments/assets/3a6bf5aa-c434-476b-a4c2-c0fd043e87b1">

**Comment by PrinceVictor** [comment]
Could you run `pip list |grep struct-eqtable`  and `git log` to show more information ?

**Comment by Faultiness** [comment]
I installed `struct-eqtable` from source code as suggested. And `pip list |grep struct-eqtable` reports the version is 0.1.0. Now I tried `pip install --upgrade struct-eqtable` and successfully upgraded the version to 0.3.0. 

And now everything seems to work well. Thanks for your help :-)

**Comment by PrinceVictor** [comment]
Glad to hear everything is working well! We welcome your attention to our open-source work and appreciate any suggestions you might have.

**Comment by Faultiness** [comment]
Thanks for your help and contribution to the open-source tabular data extraction solution. Since the problem has been located and resolved, I will close the issue.
