### ISSUE TITLE
Error running demo.py with StructTable-InternVl2-1B, Can anyone help me, Thanks!

### ISSUE THREAD

**Issue by robbiesky** [UniModal4Reasoning/StructEqTable-Deploy#18]
When run demo.py with default parameter is correct , but with the follow command is error:
python .\demo.py --image_path .\demo.png --ckpt_path U4R/StructTable-InternVL2-1B --output_format latex

The environment is windows 10, python3.10, torch 2.3.1 with cuda
The output is as follows

import tensorrt_llm failed, if do not use tensorrt, ignore this message
C:\ProgramData\anaconda3\envs\structeqtable\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
FlashAttention2 is not installed.
Supported output format: latex
Traceback (most recent call last):
  File "E:\projects\python\StructEqTable-Deploy\tools\demo\demo.py", line 70, in <module>
    main()
  File "E:\projects\python\StructEqTable-Deploy\tools\demo\demo.py", line 52, in main
    output = model(raw_image, output_format=tgt_fmt)
  File "C:\ProgramData\anaconda3\envs\structeqtable\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\structeqtable\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "e:\projects\python\structeqtable-deploy\struct_eqtable\internvl\internvl.py", line 116, in forward
    model_output = self.model.generate(
  File "C:\ProgramData\anaconda3\envs\structeqtable\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\five\.cache\huggingface\modules\transformers_modules\U4R\StructTable-InternVL2-1B\3ea09f66e8c411830f65c4acec65847aa86591b0\modeling_internvl_chat.py", line 345, in generate
    outputs = self.language_model.generate(
  File "C:\ProgramData\anaconda3\envs\structeqtable\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\structeqtable\lib\site-packages\transformers-4.46.0-py3.10.egg\transformers\generation\utils.py", line 2215, in generate
    result = self._sample(
  File "C:\ProgramData\anaconda3\envs\structeqtable\lib\site-packages\transformers-4.46.0-py3.10.egg\transformers\generation\utils.py", line 3206, in _sample
    outputs = self(**model_inputs, return_dict=True)
TypeError: Qwen2ForCausalLM(
  (model): Qwen2Model(
    (embed_tokens): Embedding(151655, 896)
    (layers): ModuleList(
      (0-23): 24 x Qwen2DecoderLayer(
        (self_attn): Qwen2Attention(
          (q_proj): Linear(in_features=896, out_features=896, bias=True)
          (k_proj): Linear(in_features=896, out_features=128, bias=True)
          (v_proj): Linear(in_features=896, out_features=128, bias=True)
          (o_proj): Linear(in_features=896, out_features=896, bias=False)
          (rotary_emb): Qwen2RotaryEmbedding()
        )
        (mlp): Qwen2MLP(
          (gate_proj): Linear(in_features=896, out_features=4864, bias=False)
          (up_proj): Linear(in_features=896, out_features=4864, bias=False)
          (down_proj): Linear(in_features=4864, out_features=896, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
      )
    )
    (norm): Qwen2RMSNorm((896,), eps=1e-06)
    (rotary_emb): Qwen2RotaryEmbedding()
  )
  (lm_head): Linear(in_features=896, out_features=151655, bias=False)
) got multiple values for keyword argument 'return_dict'

**Comment by PrinceVictor** [comment]
It seems you haven't installed flash attention. You can try [disable flash_atten](https://github.com/UniModal4Reasoning/StructEqTable-Deploy/blob/2fee2ec60b7ef2285c60ce163dccc652e279c47b/tools/demo/demo.py#L19) to see if it runs successfully.

**Comment by AlphaJi** [comment]
> It seems you haven't installed flash attention. You can try [disable flash_atten](https://github.com/UniModal4Reasoning/StructEqTable-Deploy/blob/2fee2ec60b7ef2285c60ce163dccc652e279c47b/tools/demo/demo.py#L19) to see if it runs successfully.

我也有同样的问题，而且我安装了flash-attn
![Uploading 截屏2024-10-29 17.25.29.png…]()

**Comment by PrinceVictor** [comment]
> 我也有同样的问题，而且我安装了flash-attn

@AlphaJi  The screenshot you uploaded cannot be displayed properly. Could you provide more log information?

**Comment by robbiesky** [comment]
> It seems you haven't installed flash attention. You can try [disable flash_atten](https://github.com/UniModal4Reasoning/StructEqTable-Deploy/blob/2fee2ec60b7ef2285c60ce163dccc652e279c47b/tools/demo/demo.py#L19) to see if it runs successfully.

run with --disable_flash_attn have the same problem, i will install flash attention, then try
python .\demo.py --image_path .\table1.png --ckpt_path U4R/StructTable-InternVL2-1B --disable_flash_attn --output_format html

**Comment by AlphaJi** [comment]
> > 我也有同样的问题，而且我安装了flash-attn
> 
> @AlphaJi The screenshot you uploaded cannot be displayed properly. Could you provide more log information?

<img width="1036" alt="截屏2024-10-29 17 25 29" src="https://github.com/user-attachments/assets/df902ee5-3a65-46c7-ae0c-54263fce59a2">

**Comment by AlphaJi** [comment]
而且即使--disable_flash_attn也是运行不成功的

**Comment by PrinceVictor** [comment]
> > > 我也有同样的问题，而且我安装了flash-attn
> > 
> > 
> > @AlphaJi The screenshot you uploaded cannot be displayed properly. Could you provide more log information?
> 
> <img alt="截屏2024-10-29 17 25 29" width="1036" src="https://private-user-images.githubusercontent.com/15061887/381360780-df902ee5-3a65-46c7-ae0c-54263fce59a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNTY0NjMsIm5iZiI6MTczMDI1NjE2MywicGF0aCI6Ii8xNTA2MTg4Ny8zODEzNjA3ODAtZGY5MDJlZTUtM2E2NS00NmM3LWFlMGMtNTQyNjNmY2U1OWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDAyNDI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwNWNjMTdlNzg0NmY0ZGU5YTkwYzA3NjRiNmMzY2E0MTg3MjdmMTc0NmJlMWUzZTU5MTYzMjU0ZmEwYjYzZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SKUwgSV_0M0sZ5eQo-kEzLVbp97vJv1XzJ-7bh554Ek">

@AlphaJi @robbiesky  
It seems the error is caused by different versions of the transformers package. I'm using version 4.45.2, and it appears that the latest 4.46 has made changes for Qwen2ForCausalLM class. I suggest downgrading transformers to 4.45.2 to ensure the code runs properly. I will do further verification and updates to make it compatible with the latest transformers version.

**Comment by AlphaJi** [comment]
> > > > 我也有同样的问题，而且我安装了flash-attn
> > > 
> > > 
> > > @AlphaJi The screenshot you uploaded cannot be displayed properly. Could you provide more log information?
> > 
> > 
> > <img alt="截屏2024-10-29 17 25 29" width="1036" src="https://private-user-images.githubusercontent.com/15061887/381360780-df902ee5-3a65-46c7-ae0c-54263fce59a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNTY0NjMsIm5iZiI6MTczMDI1NjE2MywicGF0aCI6Ii8xNTA2MTg4Ny8zODEzNjA3ODAtZGY5MDJlZTUtM2E2NS00NmM3LWFlMGMtNTQyNjNmY2U1OWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDAyNDI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwNWNjMTdlNzg0NmY0ZGU5YTkwYzA3NjRiNmMzY2E0MTg3MjdmMTc0NmJlMWUzZTU5MTYzMjU0ZmEwYjYzZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SKUwgSV_0M0sZ5eQo-kEzLVbp97vJv1XzJ-7bh554Ek">
> 
> @AlphaJi @robbiesky It seems the error is caused by different versions of the transformers package. I'm using version 4.45.2, and it appears that the latest 4.46 has made changes for Qwen2ForCausalLM class. I suggest downgrading transformers to 4.45.2 to ensure the code runs properly. I will do further verification and updates to make it compatible with the latest transformers version.

解决了，thanks！

**Comment by robbiesky** [comment]
> > > > 我也有同样的问题，而且我安装了flash-attn
> > > 
> > > 
> > > @AlphaJi The screenshot you uploaded cannot be displayed properly. Could you provide more log information?
> > 
> > 
> > <img alt="截屏2024-10-29 17 25 29" width="1036" src="https://private-user-images.githubusercontent.com/15061887/381360780-df902ee5-3a65-46c7-ae0c-54263fce59a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNTY0NjMsIm5iZiI6MTczMDI1NjE2MywicGF0aCI6Ii8xNTA2MTg4Ny8zODEzNjA3ODAtZGY5MDJlZTUtM2E2NS00NmM3LWFlMGMtNTQyNjNmY2U1OWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDAyNDI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwNWNjMTdlNzg0NmY0ZGU5YTkwYzA3NjRiNmMzY2E0MTg3MjdmMTc0NmJlMWUzZTU5MTYzMjU0ZmEwYjYzZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SKUwgSV_0M0sZ5eQo-kEzLVbp97vJv1XzJ-7bh554Ek">
> 
> @AlphaJi @robbiesky It seems the error is caused by different versions of the transformers package. I'm using version 4.45.2, and it appears that the latest 4.46 has made changes for Qwen2ForCausalLM class. I suggest downgrading transformers to 4.45.2 to ensure the code runs properly. I will do further verification and updates to make it compatible with the latest transformers version.

Works Fine! Thanks!

**Comment by PrinceVictor** [comment]
The StructTable-InternVL2-1B model files have been updated and are now compatible with the latest transformers version.
