### ISSUE TITLE
The demo image seems to get the wrong result

### ISSUE THREAD

**Issue by fukawachan** [UniModal4Reasoning/StructEqTable-Deploy#4]
**Question Describe:**
I can't get the standard latex output when I use the demo image.

**Problem reproduction:**

Environment:

> Python: 3.10
> CUDA: 12.1
> Torch: 2.3.1+cu121
> GPU: Tesla T4

command:
`python demo.py --image_path ./demo.png --ckpt_path /.../models/TabRec/StructEqTable/ --output_format latex`

output:
```
total cost time: 16.64s
Table 0 LATEX format output:
\begin{tabular}{l@{\hskip 0.4in}ccc@{\hskip 0.3in}ccc}\hline \multicolumn{1}{c}{\multirow{2}{*}{Model}} & \multicolumn{2}{c}{\bf MCQA} & \multicolumn{2}{c}{\bf NSP} & \multicolumn{2}{c}{\bf PI} \\\multicolumn{1}{c}{} & Accuracy & F1 & Accuracy & F1 & Accuracy & F1 \\ \hline FastText & 0.318 & 0.317 & 0.496 & 0.496 & 0.762 & 0.806 \\ELMo & 0.318 & 0.318 & 0.691 & 0.691 & 0.807 & 0.867 \\BERT & 0.346 & 0.346 & 0.514 & 0.514 & 0.801 & 0.857 \\ \hline \end{tabular}
```

command:
`python demo.py --image_path ./demo_zh.png --ckpt_path /.../models/TabRec/StructEqTable/ --output_format latex`

output:
```
total cost time: 22.82s
Table 0 LATEX format output:
\begin{table}[h]\centering\begin{tabular}{ p{2.1cm} p{1.2cm}<{\centering} p{1cm}<{\centering} p{1.2cm}<{\centering} p{1cm}<{\centering} p{1.2cm}<{\centering} p{1cm}<{\centering} }\multicolumn{1}{c}{\multirow{2}{*}{模型} } &\multicolumn{2}{c}{\textbf{MCQA}} &\multicolumn{2}{c}{\textbf{NSP}} &\multicolumn{2}{c}{\textbf{PI}} \\& 准确率 & F1 & 准确率 & F1 & 准确率 & F1 \\\hline FastText & 0.318 & 0.317 & 0.496 & 0.496 & 0.762 & 0.806\\ELMo & 0.318 & 0.318 & 0.691 & 0.691 & 0.807 & 0.867\\BERT & 0.346 & 0.346 & 0.514 & 0.514 & 0.801 & 0.857 \\\hline \end{tabular}\end{table}
```

I am not familiar with the syntax of LaTeX, but the output code seems to be unrecognizable by the LaTeX editor.

**Comment by shenxianovo** [comment]
@fukawachan 
> **Question Describe:** I can't get the standard latex output when I use the demo image.

Try this out, it should give you the right result.
The LaTeX editer I'm using is `LaTeX Workshop` , an extension in VSCode.

``` LaTeX
\documentclass{article}
\usepackage{multirow}

\begin{document}

    \begin{tabular}{l@{\hskip 0.4in}ccc@{\hskip 0.3in}ccc}\hline \multicolumn{1}{c}{\multirow{2}{*}{Model}} & \multicolumn{2}{c}{\bf MCQA} & \multicolumn{2}{c}{\bf NSP} & \multicolumn{2}{c}{\bf PI} \\\multicolumn{1}{c}{} & Accuracy & F1 & Accuracy & F1 & Accuracy & F1 \\ \hline FastText & 0.318 & 0.317 & 0.496 & 0.496 & 0.762 & 0.806 \\ELMo & 0.318 & 0.318 & 0.691 & 0.691 & 0.807 & 0.867 \\BERT & 0.346 & 0.346 & 0.514 & 0.514 & 0.801 & 0.857 \\ \hline \end{tabular}

\end{document}

```

If any other errors occur, copy the error message and ask Copilot or ChatGPT.

**Comment by fukawachan** [comment]
> @fukawachan
> 
> > **Question Describe:** I can't get the standard latex output when I use the demo image.
> 
> Try this out, it should give you the right result. The LaTeX editer I'm using is `LaTeX Workshop` , an extension in VSCode.
> 
> ```
> \documentclass{article}
> \usepackage{multirow}
> 
> \begin{document}
> 
>     \begin{tabular}{l@{\hskip 0.4in}ccc@{\hskip 0.3in}ccc}\hline \multicolumn{1}{c}{\multirow{2}{*}{Model}} & \multicolumn{2}{c}{\bf MCQA} & \multicolumn{2}{c}{\bf NSP} & \multicolumn{2}{c}{\bf PI} \\\multicolumn{1}{c}{} & Accuracy & F1 & Accuracy & F1 & Accuracy & F1 \\ \hline FastText & 0.318 & 0.317 & 0.496 & 0.496 & 0.762 & 0.806 \\ELMo & 0.318 & 0.318 & 0.691 & 0.691 & 0.807 & 0.867 \\BERT & 0.346 & 0.346 & 0.514 & 0.514 & 0.801 & 0.857 \\ \hline \end{tabular}
> 
> \end{document}
> ```
> 
> If any other errors occur, copy the error message and ask Copilot or ChatGPT.

**Thank you for your reply!**

I have tried sending the output formula to ChatGPT to help me regenerate a Latex formula that meets the specifications. But I hope to directly generate a formula that can be recognized by the Latex editor through this project. I don't know if I am the one who meet this problem (generating non-standard formulas), or if someone else is experiencing the same problem.

May you have a good day!

**Comment by BOBrown** [comment]
@fukawachan 
When I import your output into Overleaf, it compiles and renders successfully without any errors. Could you please check it  again?

![test123](https://github.com/user-attachments/assets/ee9df48d-af6e-472a-819a-83d4c760100e)

**Comment by fukawachan** [comment]
> @fukawachan When I import your output into Overleaf, it compiles and renders successfully without any errors. Could you please check it again?
> 
> ![test123](https://private-user-images.githubusercontent.com/18318394/356058096-ee9df48d-af6e-472a-819a-83d4c760100e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODQzNjYsIm5iZiI6MTcyMzA4NDA2NiwicGF0aCI6Ii8xODMxODM5NC8zNTYwNTgwOTYtZWU5ZGY0OGQtYWY2ZS00NzJhLTgxOWEtODNkNGM3NjAxMDBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDAyMjc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1MWNkNWUxZjEwZGRlNDMzNmUyODM2MTJkOTcxYzQ5NjMxOWY3Y2VhMGZjMGIzMzllMTY0MTY1ZTgyMGQxYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jfgZYY9Qf_2U-4x0F6A-EBUMyZ0jNUKbmHGld8jEQ2Q)

**Thank you for your reply!**

I have tried it In Overleaf, it also renders successfully. When I met the problem, I used MarkText, a Markdown editor that supports Latex syntax. I think there are two reasons lead to my problem: 

1. Lack of necessary library imports. The code use {multirow} package, but MarkText does not support importing Latex libraries.
2. MarkDown has relatively weak support for Latex syntax. I have tried various markdown editors, but most of them can only render some relatively simple Latex syntax. When Latex formulas are complex (such as those listed earlier), the Markdown editor cannot render them.

As I need to display tables in Markdown text, I will further try to solve the problem I have encountered. The current issue can be closed, and there is no problem with the formula generated for the demo image of this project.

May you have a nice day!
